//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogAnalyzer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogAnalyzer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max entries per list.
        /// </summary>
        public static string MaxEntriesPerList {
            get {
                return ResourceManager.GetString("MaxEntriesPerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show live chart.
        /// </summary>
        public static string ShowLiveChart {
            get {
                return ResourceManager.GetString("ShowLiveChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show pattern match panel.
        /// </summary>
        public static string ShowPatternMatchPanel {
            get {
                return ResourceManager.GetString("ShowPatternMatchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to synchronization tolerance.
        /// </summary>
        public static string SynchronizationTolerance {
            get {
                return ResourceManager.GetString("SynchronizationTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync selection across lists.
        /// </summary>
        public static string SyncSelectionAcrossLists {
            get {
                return ResourceManager.GetString("SyncSelectionAcrossLists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show file explorer in log lists.
        /// </summary>
        public static string ShowFileExplorerInLogLists {
            get {
                return ResourceManager.GetString("ShowFileExplorerInLogLists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show mini map in scrollbar.
        /// </summary>
        public static string ShowMiniMap {
            get {
                return ResourceManager.GetString("ShowMiniMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Explorer root folder.
        /// </summary>
        public static string ExplorerRootFolder {
            get {
                return ResourceManager.GetString("ExplorerRootFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current path as root.
        /// </summary>
        public static string CurrentPathAsRoot {
            get {
                return ResourceManager.GetString("CurrentPathAsRoot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto-reload log files.
        /// </summary>
        public static string AutoReloadLogFiles {
            get {
                return ResourceManager.GetString("AutoReloadLogFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date column sorting.
        /// </summary>
        public static string DateColumnSorting {
            get {
                return ResourceManager.GetString("DateColumnSorting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Newest entries on top (descending).
        /// </summary>
        public static string NewestEntriesOnTopDescending {
            get {
                return ResourceManager.GetString("NewestEntriesOnTopDescending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Oldest entries on top (ascending).
        /// </summary>
        public static string OldestEntriesOnTopAscending {
            get {
                return ResourceManager.GetString("OldestEntriesOnTopAscending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Live chart.
        /// </summary>
        public static string LiveChart {
            get {
                return ResourceManager.GetString("LiveChart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pattern match panel.
        /// </summary>
        public static string PatternMatchPanel {
            get {
                return ResourceManager.GetString("PatternMatchPanel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tolerance (hh:mm:ss).
        /// </summary>
        public static string ToleranceHhMmSs {
            get {
                return ResourceManager.GetString("ToleranceHhMmSs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Highlight rules.
        /// </summary>
        public static string HighlightRules {
            get {
                return ResourceManager.GetString("HighlightRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search text:.
        /// </summary>
        public static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add rule.
        /// </summary>
        public static string AddRule {
            get {
                return ResourceManager.GetString("AddRule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active rules:.
        /// </summary>
        public static string ActiveRules {
            get {
                return ResourceManager.GetString("ActiveRules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open active rules in a separate window.
        /// </summary>
        public static string OpenActiveRulesInWindow {
            get {
                return ResourceManager.GetString("OpenActiveRulesInWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset defaults.
        /// </summary>
        public static string ResetDefaults {
            get {
                return ResourceManager.GetString("ResetDefaults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log Pattern Editor.
        /// </summary>
        public static string LogPatternEditor {
            get {
                return ResourceManager.GetString("LogPatternEditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage log pattern templates.
        /// </summary>
        public static string ManageLogPatternTemplates {
            get {
                return ResourceManager.GetString("ManageLogPatternTemplates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 📋 Open Pattern Editor.
        /// </summary>
        public static string OpenPatternEditor {
            get {
                return ResourceManager.GetString("OpenPatternEditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create, edit, and test log pattern templates for automatic error detection.
        /// </summary>
        public static string CreateEditAndTestLogPatternTemplates {
            get {
                return ResourceManager.GetString("CreateEditAndTestLogPatternTemplates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        public static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy text.
        /// </summary>
        public static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply as global search.
        /// </summary>
        public static string ApplyAsGlobalSearch {
            get {
                return ResourceManager.GetString("ApplyAsGlobalSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to pattern.
        /// </summary>
        public static string AddToPattern {
            get {
                return ResourceManager.GetString("AddToPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply selection as filter.
        /// </summary>
        public static string ApplySelectionAsFilter {
            get {
                return ResourceManager.GetString("ApplySelectionAsFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply selection as global search.
        /// </summary>
        public static string ApplySelectionAsGlobalSearch {
            get {
                return ResourceManager.GetString("ApplySelectionAsGlobalSearch", resourceCulture);
            }
        }
    }
}
